config/routes.rb
Contractr::Application.routes.draw do

  devise_for :users
  resources :users, only: [:show] do
    resources :clients
    resources :jobs
  end

  root to: 'static_pages#home'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :city, :email, :name, :phone, :state, :street, :zip

  belongs_to :user

  before_validation { |client| client.phone = phone.gsub(/\D/, '') }

  before_save { |client| client.email = email.downcase }

	validates :email, format: { with: VALID_EMAIL_REGEX }, allow_blank: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, length: { is: 10, message: "numbers should have 10 digits"  }, allow_blank: true
  validates :state, presence: true
  validates :zip, numericality: { only_integer: true }, length: { is: 5, message: "codes should have 5 digits" }, allow_nil: true
  validates_presence_of :user
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :is_bid, :is_billed, :is_paid, :name, :work_items_attributes

  # TODO: inverse_of ?
  belongs_to :user
  belongs_to :client
  has_many :work_items, :inverse_of => :job, :dependent => :destroy
  accepts_nested_attributes_for :work_items, 
    reject_if: lambda { |a| a[:work_category_id].blank? },
    allow_destroy: true

  # default value
  before_validation { |job| job.is_bid ||= true }

  validates :name, presence: true, length: { maximum: 150 }
  validate :validate_has_work_items
  validates_presence_of :client
  validates_presence_of :user

  def validate_has_work_items
    errors.add(:work_items, "must have some work items") if work_items.length < 1
  end

  def total_cost
    sum = 0
    work_items.each do |item|
      sum += item.client_cost
    end
    sum
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :business, :password, :password_confirmation, :remember_me

  devise :database_authenticatable, :registerable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  #TODO:  This will be converted to relationship on a business
  #       model at a later date.
  has_many :jobs, :inverse_of => :user, :dependent => :destroy
  has_many :clients, :inverse_of => :user, :dependent => :destroy

  before_save { |user| user.email = email.downcase }

	validates :email, format: { with: VALID_EMAIL_REGEX }, allow_blank: true
  validates :name, length: { maximum: 50 }, presence: true
  validates :business, length: { maximum: 50 }, presence: true
end

app/models/work_category.rb
class WorkCategory < ActiveRecord::Base
  attr_accessible :is_taxable, :labor_time_per_unit, :name, :price_per_unit, :unit

  validates :name, presence: true, length: { maximum: 50 }
  validates :labor_time_per_unit, presence: true
  validates :price_per_unit, presence: true
  validates :unit, presence: true
  validates :is_taxable, inclusion: { in: [true, false], message: 'requires a true or false value' }
end

app/models/work_item.rb
class WorkItem < ActiveRecord::Base
  attr_accessible :work_amount, :work_category_id

  belongs_to :work_category
  belongs_to :job, :inverse_of => :work_items

  validates :work_amount, numericality: { only_integer: true },  presence: true
  # The following results in small perf penalty but better db integrity
  validates_presence_of :work_category
  validates_presence_of :job

  def client_cost
    work_category.price_per_unit * work_amount
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @client = Client.new
  end

  def create
    @client = current_user.clients.new(params[:client])
    if @client.save
      flash[:success] = "Created new client"
      redirect_to user_client_path(current_user, @client)
    else
      render 'new'
    end
  end

  def show
    @client = current_user.clients.find(params[:id])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @client = Client.new( name: "New Client")
    @job = Job.new( name: "New Job")
    @job.work_items.new
  end

  def create
    @client = current_user.clients.new(params[:client])
    @job = current_user.jobs.new(params[:job])
    @job.client = @client
    if(@client.valid?)
      if(@job.save)
        redirect_to user_job_path(current_user, @job)
      else
        render 'new'
      end
    else
      @job.valid?
      render 'new'
    end
  end

  def update
    logger.debug(params.inspect)
  end

  def show
    @job = current_user.jobs.find(params[:id])
  end

  def index
    @jobs = current_user.jobs.all #paginate this shit later
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    if(current_user.id.to_s == params[:id])
      @user = current_user
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Contractr"
		if page_title.empty?
			base_title
		else
      #TODO: still don't totally understanding what is escaping what
		  "#{base_title} | #{page_title}".html_safe 
		end
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/view_helper.rb
module ViewHelper
  def icon_ok_remove(status)
    if status
      '<i class="icon-ok"></i>'.html_safe
    else
      '<i class="icon-remove"></i>'.html_safe
    end
  end
end

app/views/clients/new.html.erb
<% provide(:title, 'Add New Client') %>
<h1>Add New Client</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for([current_user, @client]) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :street %>
      <%= f.text_field :street %>

      <%= f.label :city %>
      <%= f.text_field :city %>

      <%= f.label :state %>
      <%= f.text_field :state %>

      <%= f.label :zip %>
      <%= f.text_field :zip %>

      <%= f.label :phone %>
      <%= f.telephone_field :phone %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <br>
      <%= f.submit "Create New Client", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/clients/show.html.erb
<% provide(:title, @client.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @client.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <ul>
      <li>Name: <%= @client.name %></li>
      <li>Phone: <%= @client.phone %></li>
      <li>Email: <%= @client.email %></li>
      <li>Street: <%= @client.street %></li>
      <li>City: <%= @client.city %></li>
      <li>State: <%= @client.state %></li>
      <li>Zip: <%= @client.zip %></li>
    </ul>
  </div>
      
</div>

app/views/jobs/_job_form.html.erb
<%= nested_form_for([current_user, @job]) do |f| %>

  <%= render 'shared/error_messages', object: @client %>

  <div class="span10">
    <%= render 'shared/client_fields', builder: f %>

    <br><br>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name, "Job Name" %>
    <%= f.text_field :name, class: 'input-medium' %>
  </div>

  <%= render 'work_item_table', builder: f %>

  <div class="span10 align-right">
    <%= f.submit "#{form_action} Job", class: "btn btn-large btn-primary" %>
  </div>
<% end %>

<script>
  // TODO: verify that printing raw(from db...) is secure
  contractr.work_categories = <%= raw @work_categories.to_json(only: [:id, :name, :price_per_unit, :unit]) %>
</script>

app/views/jobs/_work_item_table.html.erb
<table class="job-table span10">
  <caption><h4>Work Items</h4></caption>
  <thead>
    <tr>
      <th>Task</th>
      <th>Unit Price</th>
      <th>Quantity</th>
      <th class="cost-column">Cost</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="work-item-body">
    <%= builder.fields_for :work_items, wrapper: false do |wi_form| %>

      <% item_id = @job.work_items.index(wi_form.object) %>
      <tr class="work-items fields" data-column="<%= item_id %>">
        <td>
          <%= wi_form.collection_select(:work_category_id, @work_categories, 
                                        :id, :name, { include_blank: true }, 
                                        { class: 'input-medium' }) %>
        </td>

        <td class="category-detail"></td>

        <td class="work-item-amount">
          <%= wi_form.text_field :work_amount, class: "input-small" %>
          <%= wi_form.label :work_amount, "&nbsp".html_safe %>
        </td>

        <td class="work-item-cost cost-column"> </td>

        <td class="work-item-delete">
          <%= wi_form.link_to_remove 'Remove Item 
          <i class="icon-remove-sign icon-white"></i>
          '.html_safe, class: "btn btn-danger" %>
          
        </td>
      </tr>

    <% end %>
    <tr>
      <td>
        <%= builder.link_to_add 'Add a Work Item 
        <i class="icon-plus-sign icon-white"></i>
        '.html_safe, :work_items, class: "btn btn-success"%>
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td id="job-total-cost" class="cost-column">0</td>
      <td></td>
    </tr>
  </tfoot>
</table>

app/views/jobs/create.html.erb
<h1>Jobs#create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/index.html.erb
<% provide(:title, 'Jobs Index') %>

<h1>All Jobs</h1>
<div class="row">
  <% @jobs.each do |job| %>

    <div id="job_<%= job.id %>" class="job-box">
      <a href="<%= user_job_path(current_user, job) %>"><span class="expand"></span></a> 
      <h3><%= job.name %></h3> 
      <br>
      <table class="compact-client-table">
        <tbody>
          <tr>
            <td><%= job.client.name %></td>
            <td><%= job.client.phone %></td>
            <td><%= job.client.city %>, <%= job.client.state %></td>
          </tr>
        </tbody>
      </table>
      <br>
      <table class="compact-table span6">
        <thead>
          <tr>
            <th>Work</th>
            <th></th>
            <th>Cost</th>
          </tr>
        </thead>
        <tbody>
          <% job.work_items.all.each do |item| %>
            <tr>
              <td><%= item.work_category.name %></td>
              <td></td>
              <td><%= item.client_cost %></td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td>Total Cost</td>
            <td></td>
            <td><%= job.total_cost %></td>
          </tr>
        </tfoot>
      </table>
      <br>
      <div> 
        <span class="bid">Bid <%= icon_ok_remove job.is_bid? %></span>
        <span class="billed">Billed <%= icon_ok_remove job.is_billed? %></span>
        <span class="paid">Paid <%= icon_ok_remove job.is_paid? %></span>
      </div>
    </div>
  <% end %>
</div>

app/views/jobs/new.html.erb
<% @work_categories = WorkCategory.all %>

<% provide(:title, 'New Job') %>

<h1>Create New Job</h1>
<div class="row">
  <div class="span12 offset1">
    <%= render 'job_form', form_action: 'Save' %>
  </div>
</div>

app/views/jobs/show.html.erb
<% provide(:title, @job.name) %>

<h1>Job: <%= @job.name %></h1>
<div class="row">
  <div class="span12">
    <div class="coolz"><%= @job.client.name %></div>
    <div class="client-line"><%= @job.client.street %></div>
    <div class="client-line"><%= @job.client.city %>, <%= @job.client.state %> <%= @job.client.zip %></div>
    <br>
    <div class="client-line"><%= @job.client.phone %></div>
    <div class="client-line"><%= @job.client.email %></div>
    <br>

    <table class="job-table span10">
      <thead>
        <tr>
          <th>Task</th>
          <th>Quantity</th>
          <th class="cost-column">Cost</th>
        </tr>
      </thead>
      <tbody id="work-item-body">
        <% @job.work_items.all.each do |item| %>

          <tr class="work-items fields">
            <td>
              <%= item.work_category.name %>
            </td>

            <td class="work-item-amount">
              <strong><%= item.work_amount %></strong>
              <small>at</small>
              <%= item.work_category.price_per_unit %>
              <small>per</small>
              <%= item.work_category.unit %>
            </td>

            <td class="work-item-cost cost-column">
              <%= item.client_cost %>
            </td>
          </tr>

        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td></td>
          <td></td>
          <td id="job-total-cost" class="cost-column">
            Total: <%= @job.total_cost %>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small> Contactr </small>
  <nav>
    <ul>
      <li>Developed by Jacob Dalton</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse"> <div class="navbar-inner">
	<div class="container">
    <%= link_to "Contractr", root_path, id: "logo" %>
	  <nav>
		<ul class="nav pull-right">
      <% if user_signed_in? %>
        <li>
          <%= link_to "New Job", new_user_job_path(current_user) %>
        </li>
        <li>
          <%= link_to "All Jobs", user_jobs_path(current_user) %>
        </li>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: 'delete' %>
        </li>
        <li>
          <%= link_to "Profile", user_path(current_user) %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign in", new_user_session_path %>
        </li>
      <% end %>
		</ul>
	  </nav>
	</div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>       
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
  </head>
  <body>
	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_client_fields.html.erb
<%= fields_for :client, @client do |f| %>

  <table class="client-table">
    <thead>
      <tr>
        <th><%= f.label :name, "Client Name"  %></th>
        <th><%= f.label :phone %></th>
        <th><%= f.label :email %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= f.text_field :name, class: 'input-medium' %></td>
        <td><%= f.telephone_field :phone, class: 'input-small' %></td>
        <td><%= f.text_field :email, class: 'input-large' %></td>
      </tr>
    </tbody>
  </table>

  <table class="client-table">
    <thead>
      <tr>
        <th><%= f.label :street %></th>
        <th><%= f.label :city %></th>
        <th><%= f.label :state %></th>
        <th><%= f.label :zip %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= f.text_field :street %></td>
        <td><%= f.text_field :city, class: 'input-small' %></td>
        <td><%= f.text_field :state, class: 'input-mini' %></td>
        <td><%= f.text_field :zip, class: 'input-mini' %></td>
      </tr>
    </tbody>
  </table>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'New Job') %>

<h1>Home</h1>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>Name: <%= @user.name %></h1>
<p>Email: <%= @user.email %></p>
<p>Business: <%= @user.business %></p>